import { Poppins, Michroma } from "next/font/google";
import "../app/styles/globals.css";
import "../app/styles/custom-button.css";
import "@splidejs/splide/dist/css/splide.min.css";
import "aos/dist/aos.css";
import Header from "@/components/Header";
import NavMenu from "@/components/NavMenu";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: ["400"], // Michroma only has one weight
});

export const metadata = {
  title: "Adoram Tom's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${michroma.variable}`}>
      <body className="font-sans antialiased">
        <Header />
        {children}
        <NavMenu />
        <Footer />
      </body>
    </html>
  );
}

